### ISSUE TITLE
missing list file for training and validation data

### ISSUE THREAD

**Issue by amiltonwong** [tomztyang/3DSSD#1]
Hi, @tomztyang ,

According to [data-preparation](https://github.com/tomztyang/3DSSD#data-preparation)  , several list file for training and validation data (train.txt, test.txt val.txt, trainval.txt) are required. However, they are not provided by the official benchmark website. Could you provide them here?

THX!

**Comment by tomztyang** [comment]
Hi @amiltonwong ,
I have provided train.txt and val.txt here. The trainval.txt is just the merged version of these two former files. 

Thank you so much.
[train.txt](https://github.com/tomztyang/3DSSD/files/4491173/train.txt)
[val.txt](https://github.com/tomztyang/3DSSD/files/4491174/val.txt)

**Comment by amiltonwong** [comment]
Hi, @tomztyang ,

Thanks for your reply. One more file is missing: test.txt. Could you also provide it?

THX!

**Comment by tomztyang** [comment]
Added~ 

Regards,
Zetong
[test.txt](https://github.com/tomztyang/3DSSD/files/4491574/test.txt)
