### ISSUE TITLE
Filtering Point Cloud Range

### ISSUE THREAD

**Issue by Divadi** [tomztyang/3DSSD#13]
Hi, looking at the Point cloud range here:
https://github.com/Jia-Research-Lab/3DSSD/blob/8bc7605d4d3a6ec9051e7689e96a23bdac4c4cd9/configs/kitti/3dssd/3dssd.yaml#L3
I saw that the vertical filter was set to include point cloud -5 ~ 3, which I found is generally the range for kitti lidar in velodyne coordinates. However in here:
https://github.com/Jia-Research-Lab/3DSSD/blob/8bc7605d4d3a6ec9051e7689e96a23bdac4c4cd9/lib/dataset/dataloader/kitti_dataloader.py#L192
the point cloud is filtered after transforming to rect. camera coordinates, and I found that the vertical range in rect camera coordinate is -3 ~ 5.

Is it intentional for the kitti_dataloader to filter after transforming to rect. camera coords?

**Comment by tomztyang** [comment]
In our implementation, the point cloud is transferred to the rect coordinate first. However, if you wish to use it in the velodyne coordinate like NuScenes dataset, you have to transfer the point cloud like:
points_xyz = points[:, :3]
points_xyz = points_xyz[:, [0, 2, 1]]
points_xyz[:, 1] = -points_xyz[:, 1]
points[:, :3] = points_xyz
