### ISSUE TITLE
Valid Checkpoint Path

### ISSUE THREAD

**Issue by deeptibhegde** [tomztyang/3DSSD#14]
Hello,
I apologize if this is an overly simplistic question, but I have trained the model and generated the log files. When I go to run evaluator or tester, it says model not found or please "provide valid checkpoint path", respectively. May I know which path I should give exactly, if not the log path?

**Comment by deeptibhegde** [comment]
I was able to fix this by giving --split testing and --no_gt for evaluation. Still not sure if this was the correct thing to do. I suggest an update to the instructions.

**Comment by tomztyang** [comment]
Hi,
If the path of a generated log file is like this /PATH/TO/WEIGHT/log_train.txt, the valid checkpoint path is like:
1. /PATH/TO/WEIGHT - The model will evaluate the latest checkpoint within this path.
2. /PATH/TO/WEIGHT/model.ckpt-xxxx - The model will evaluate the checkpoint named as model.ckpt-xxxx

**Comment by deeptibhegde** [comment]
Hi,
But my log directory does not have a model.ckpt-xxxx checkpoint generated. Also, why is the --img_list options in tester.py only limited to val and training? Why no test images list?

**Comment by deeptibhegde** [comment]
Hi,
When I trained your model, my log directory did not have a model.ckpt-xxxx
checkpoint generated. Also, why is the --img_list options in tester.py only
limited to val and training? Why no test images list?

Thank you

**Comment by tomztyang** [comment]
That is so weird. You mean no checkpoint file is generated during training?
For the second question, we haven't tested that case for the tight schedule. Maybe you can try to implement it.

Thanks!

**Comment by Divadi** [comment]
Regarding loading the model, I found that ...log_folder/model-{epoch_num} works.

**Comment by deeptibhegde** [comment]
Okay I will try that, thank you.

**Comment by deeptibhegde** [comment]
Hello,
One more query: In kitti_dataloader.py, in what case will sample_dict be
None? I have augmented the kitti files and when I run data_preprocessor.py,
some npy files are not saved because of this error.

Thank You
