### ISSUE TITLE
points_to_voxel operation not working

### ISSUE THREAD

**Issue by Divadi** [tomztyang/3DSSD#16]
Hello, regarding the points_to_voxel function in https://github.com/Jia-Research-Lab/3DSSD/blob/8bc7605d4d3a6ec9051e7689e96a23bdac4c4cd9/lib/builder/voxel_generator/point_cloud_ops.py#L65 the returned voxel array seems to just be an array of zeros.

To test this, I simply ran:
```
import numpy as np
from lib.builder.voxel_generator.point_cloud_ops import points_to_voxel

points = np.array([
    [1, 1, 1, 0],
    [2, 2, 2, 0],
    [2.1, 2, 2, 0]
])
voxel_size = np.array([0.5, 0.5, 0.5])
coors_range = np.array([-5, -5, -5, 5, 5, 5])
max_points = 3
max_voxels = 10
voxels, num_points_per_voxel = points_to_voxel(
                                    points=points,
                                    voxel_size=voxel_size,
                                    coors_range=coors_range,
                                    max_points=max_points,
                                    max_voxels=max_voxels
                                )
print("Voxels shape:", voxels.shape)
print("Voxels:", voxels)
print("num_points_per_voxel shape:", num_points_per_voxel.shape)
print("num_points_per_voxel:", num_points_per_voxel)
```
and got the result:
```
Voxels shape: (2, 3, 4)
Voxels: [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
num_points_per_voxel shape: (2,)
num_points_per_voxel: [1 2]
```
which is not correct. However, it does seem to have correctly figured out the num_points_per_voxel, so it seems to be doing some work at least. How might I fix this issue?

Thank you for your help.

**Comment by tomztyang** [comment]
I haven' tested that operation since it is not useful in reproducing our KITTI result. You can check whether your data type is right. As illustrated in points2voxel.cpp, the data type of input point cloud should be np.float32.
