### ISSUE TITLE
some question about preprocess original dataset

### ISSUE THREAD

**Issue by Blinjuan** [tomztyang/3DSSD#17]
Hi, thanks for your impressive work, i use tensorflow1.4.0 according to your tutorial ,but i meet some errors when i try to preprocess original dataset.
when i use commmad "python lib/core/data_preprocessor.py --cfg configs/kitti/3dssd/3dssd.yaml --split training --img_list train" it works.
and  i also try  to  use command"python lib/core/data_preprocessor.py --cfg configs/kitti/3dssd/3dssd.yaml --split training --img_list val" it works

however, when i try to prepare test set and i use "python lib/core/data_preprocessor.py --cfg configs/kitti/3dssd/3dssd.yaml --split testing --img_list test"

![图片](https://user-images.githubusercontent.com/66398813/85104359-0d0d2000-b23b-11ea-84bd-330321d750c5.png)
it seems that  AttributeError: 'KittiDataset' object has no attribute 'mixup_db_class' . Could you help me fix up it，thanks a lot.

**Comment by deeptibhegde** [comment]
See issue #9
