### ISSUE TITLE
Can this run with cuda 10.0?

### ISSUE THREAD

**Issue by sarimmehdi** [tomztyang/3DSSD#23]
Hello. I see your code has been tested with cuda 9.0 and I wanted to know whether it could also be run on cuda 10.0? Please let me know, thanks!

**Comment by easyfcn** [comment]
I want to know too. Thanks!

**Comment by meng-zha** [comment]
This issue has been closed, so could someone tell me whether 3DSSD can run with cuda-10 ?
Thanks so much.

**Comment by zye1996** [comment]
> This issue has been closed, so could someone tell me whether 3DSSD can run with cuda-10 ?
> Thanks so much.

Yes, I can confirm it works under cuda 10.1+TF1.14. I made modification to the compile_all.sh and you can check my forked repo.

**Comment by daxiongpro** [comment]
> > This issue has been closed, so could someone tell me whether 3DSSD can run with cuda-10 ?
> > Thanks so much.
> 
> Yes, I can confirm it works under cuda 10.1+TF1.14. I made modification to the compile_all.sh and you can check my forked repo.

do you know how to run it on cuda11?
