### ISSUE TITLE
About the planes for test dataset

### ISSUE THREAD

**Issue by xjsong99** [tomztyang/3DSSD#3]
Thanks for your excellent work.
I have already trained the model but could you please provide the plane files for test dataset?
I wonder whether the planes influence the result a lot.

**Comment by xjsong99** [comment]
And do the APs listed in this GitHub, [91.71, 83.30, 80.44], belong to the latest model you trained? I found that it is different with the APs of 3D detection in your paper which is [89.71, 79.45, 78.67].

**Comment by tomztyang** [comment]
We don't have plane files for test. Planes are only useful in data augmentation. The APs provided are tested on R40 metrics. The original mAP provided in paper are evaluated on R11.
