### ISSUE TITLE
How to organize dataset

### ISSUE THREAD

**Issue by daxiongpro** [tomztyang/3DSSD#41]
I cannot find train.txt, val.txt, test.txt, trainval.txt, where can I get it?

**Comment by daxiongpro** [comment]
and how to organize "testing" directory?

**Comment by Antonskoltech** [comment]
the same problem

**Comment by Physu** [comment]
please refer https://github.com/open-mmlab/mmdetection3d dataset split instruction.

**Comment by daxiongpro** [comment]
> please refer https://github.com/open-mmlab/mmdetection3d dataset split instruction.

oh, I've already solve the problem
