### ISSUE TITLE
Will you provide a docker for use?

### ISSUE THREAD

**Issue by Xiangzhaohong** [tomztyang/3DSSD#5]
If there is a docker image to use, it could be very nice!

Thanks a lot!!

**Comment by tomztyang** [comment]
Hi Hong,
I cannot install docker on the server in our school because of the rules.  Therefore, docker images are not available right now.

**Comment by Xiangzhaohong** [comment]
Thanks, I'll try it , if my docker work, I can commit my image.

**Comment by tomztyang** [comment]
@Xiangzhaohong 
Thank you so much!

**Comment by abhigoku10** [comment]
@Xiangzhaohong  can you share your docker image !!

**Comment by Xiangzhaohong** [comment]
@abhigoku10 see the issue4

**Comment by abhigoku10** [comment]
@Xiangzhaohong  i am not able to download from baidu , is it possible to share it in google drive that would be really helpful

**Comment by Xiangzhaohong** [comment]
@abhigoku10 my internet can't use google . I will try tonight

**Comment by abhigoku10** [comment]
@Xiangzhaohong thanks a lot . did u train the model for pedestrians ?? how were the results

**Comment by Xiangzhaohong** [comment]
@abhigoku10 I only have trained  the car
