### ISSUE TITLE
 No module named 'core'

### ISSUE THREAD

**Issue by developer-huang** [tomztyang/3DSSD#50]
When executing a command：python lib/core/data_preprocessor.py --cfg configs/kitti/3dssd/3dssd.yaml --split training --img_list train

Traceback (most recent call last):
 File "lib/core/data_preprocessor.py", line 7, in <module>
from core.config import cfg, cfg_from_file, cfg_from_list, assert_and_infer_cfg
ModuleNotFoundError: No module named 'core' No module named 'core'

**Comment by Gaviaa** [comment]
你解决了吗，请问

**Comment by developer-huang** [comment]
不好意思，我也没有；但后来借用mmlab的mmdetection3d实现了3DSSD的复现，你可以试一下。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月28日 16:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [dvlab-research/3DSSD] No module named 'core' (Issue #50) |

你解决了吗，请问

**Comment by Gaviaa** [comment]
好的，十分感谢
