### ISSUE TITLE
mixup database in preprocessing

### ISSUE THREAD

**Issue by wildcat5566** [tomztyang/3DSSD#9]
Hello,

https://github.com/Jia-Research-Lab/3DSSD/blob/master/lib/dataset/dataloader/kitti_dataloader.py#L292

Should 

`if cfg.TRAIN.AUGMENTATIONS.MIXUP.OPEN`

be

`if cfg.TRAIN.AUGMENTATIONS.MIXUP.OPEN and self.img_list in ['train', 'val', 'trainval']` ?

If else, running command

`$ python lib/core/data_preprocessor.py --cfg configs/kitti/3dssd/3dssd.yaml --split testing --img_list test`

would generate following error:
```
File "/path/to/3DSSD/lib/dataset/dataloader/kitti_dataloader.py", line 293, in preprocess_batch
mixup_label_dict = dict([(cls, []) for cls in self.mixup_db_class])
AttributeError: 'KittiDataset' object has no attribute 'mixup_db_class'
```

**Comment by Royaler** [comment]
i also meet the same problem @tomztyang

**Comment by tomztyang** [comment]
Yes. Since there is no ground truth file on KITTI testing set, it is impossible to generate its corresponding mixup dataset.
